name: Build and deploy to github pages
on: "schedule(* 23 * * *)" # Run at the end of every day (UTC) https://jasonet.co/posts/scheduled-actions/
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3 # https://github.com/marketplace/actions/deploy-to-github-pages
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          TARGET_FOLDER: docs # The folder the action should deploy to.
          FOLDER: docs # The folder the action should deploy.